#!/bin/bash
#Este es el documento README de mi 0x03. Shell, init files, variables and expansions.
#0. Create a script that creates an alias.
#1. Hello you - Create a script that prints hello user, where user is the current Linux user.
#2. The path to success is to take massive, determined action - Add /action to the PATH. /action should be the last directory the shell looks into when looking for a program.
#3. If the path be beautiful, let us not ask where it leads - Create a script that counts the number of directories in the PATH.
#4. Global Variables - Create a script that lists environment variables.
#5. Local Variables - Create a script that lists all local variables and environment variables, and functions.
#6. Local Variables - Create a script that creates a new local variable.
#7. Global Variable - Create a script that creates a new global variable..
#8. Every addition to true knowledge is an addition to human power - Write a script that prints the result of the addition of 128 with the value stored in the environment variable TRUEKNOWLEDGE, followed by a new line.
#9. Divide and rule - Write a script that prints the result of POWER divided by DIVIDE, followed by a new line.
#10. Love is anterior to life, posterior to death, initial of creation, and the exponent of breath - Write a script that displays the result of BREATH to the power LOVE
#11. There are 10 types of people in the world -- Those who understand binary, and those who don't - Write a script that converts a number from base 2 to base 10.
#12. Combination - Create a script that prints all possible combinations of two letters, except oo
#13. Floats - Write a script that prints a number with two decimal places, followed by a new line. The number will be stored in the environment variable NUM. 
