#!/usr/bin/env bash
#this script displays I am invincible!!! when receiving a SIGTERM signal


trap "echo 'I am invincible!!!'" SIGTERM

for (( ;  ;  ))
do
    echo "To infinity and beyond"
    sleep 2
done
