#!/bin/bash/env bash
#This script displays Best School 10 times using WHILE/if/elif function.
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

count=1
while [ $count -le 10 ]
do 
echo "$Best School"
if [ $count == 4 ]
then
echo "$bad luck"

elif [ $count == 8 ]
then
echo "$good luck"

fi
((count++))
done
